import type { WeeklyPuzzle, KnowledgeSummary } from '@/types/puzzle';

// Static puzzle registry — regenerated by: npm run build:puzzles
import housing_homeless from '@/data/generated/puzzles/housing-homeless.json';
import people_farmers from '@/data/generated/puzzles/people-farmers.json';
import people_no_internet from '@/data/generated/puzzles/people-no-internet.json';
import transportation_electric_cars from '@/data/generated/puzzles/transportation-electric-cars.json';
import summary_global_agriculture from '@/data/summaries/summary_global_agriculture.json';
import summary_global_electric_vehicles from '@/data/summaries/summary_global_electric_vehicles.json';
import summary_global_homelessness from '@/data/summaries/summary_global_homelessness.json';
import summary_internet_access from '@/data/summaries/summary_internet_access.json';

const PUZZLES: WeeklyPuzzle[] = [
  housing_homeless as WeeklyPuzzle,
  people_farmers as WeeklyPuzzle,
  people_no_internet as WeeklyPuzzle,
  transportation_electric_cars as WeeklyPuzzle,
];

const SUMMARIES: KnowledgeSummary[] = [
  summary_global_agriculture as KnowledgeSummary,
  summary_global_electric_vehicles as KnowledgeSummary,
  summary_global_homelessness as KnowledgeSummary,
  summary_internet_access as KnowledgeSummary,
];

/** Week-to-puzzle schedule (ISO week → puzzle id). */
const SCHEDULE: Record<string, string> = {
  "2026-W35": "housing-homeless",
  "2026-W36": "people-no-internet",
  "2026-W37": "people-farmers",
  "2026-W38": "transportation-electric-cars",
};

/** Returns the ISO week string for a given date, e.g. "2026-W35". */
function getISOWeekId(date: Date = new Date()): string {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayOfWeek = d.getUTCDay() || 7; // Monday = 1 ... Sunday = 7
  d.setUTCDate(d.getUTCDate() + 4 - dayOfWeek);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const weekNumber = Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
  return `${d.getUTCFullYear()}-W${String(weekNumber).padStart(2, '0')}`;
}

/** Returns a monotonically increasing week index, stable across years. */
function getAbsoluteWeekIndex(date: Date = new Date()): number {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dow = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() - (dow - 1)); // rewind to Monday
  const EPOCH_MS = Date.UTC(2000, 0, 3);    // Monday 2000-01-03
  return Math.round((d.getTime() - EPOCH_MS) / (7 * 24 * 60 * 60 * 1000));
}

/**
 * Returns the puzzle for the current ISO week.
 * Looks up the week in the schedule; falls back to cycling when not found.
 */
export function getCurrentWeeklyPuzzle(): WeeklyPuzzle {
  const weekId = getISOWeekId();
  const puzzleId = SCHEDULE[weekId];
  if (puzzleId) {
    const match = PUZZLES.find((p) => p.id === puzzleId);
    if (match) return match;
  }

  // No puzzle scheduled for this week — cycle through available puzzles
  const sorted = [...PUZZLES].sort((a, b) => a.publish_date.localeCompare(b.publish_date));
  return sorted[getAbsoluteWeekIndex() % sorted.length];
}

export function getPuzzleById(id: string): WeeklyPuzzle | null {
  return PUZZLES.find((p) => p.id === id) ?? null;
}

export function getSummaryById(id: string): KnowledgeSummary | null {
  return SUMMARIES.find((a) => a.id === id) ?? null;
}
