import type { WeeklyPuzzle, KnowledgeSummary } from '@/types/puzzle';

// Static puzzle registry — regenerated by: npm run build:puzzles
import puzzle_2026_w35 from '@/data/generated/puzzles/puzzle_2026_w35.json';
import puzzle_2026_w36 from '@/data/generated/puzzles/puzzle_2026_w36.json';
import puzzle_2026_w37 from '@/data/generated/puzzles/puzzle_2026_w37.json';
import puzzle_2026_w38 from '@/data/generated/puzzles/puzzle_2026_w38.json';
import summary_global_agriculture from '@/data/summaries/summary_global_agriculture.json';
import summary_global_electric_vehicles from '@/data/summaries/summary_global_electric_vehicles.json';
import summary_global_homelessness from '@/data/summaries/summary_global_homelessness.json';
import summary_internet_access from '@/data/summaries/summary_internet_access.json';

const PUZZLES: WeeklyPuzzle[] = [
  puzzle_2026_w35 as WeeklyPuzzle,
  puzzle_2026_w36 as WeeklyPuzzle,
  puzzle_2026_w37 as WeeklyPuzzle,
  puzzle_2026_w38 as WeeklyPuzzle,
];

const SUMMARIES: KnowledgeSummary[] = [
  summary_global_agriculture as KnowledgeSummary,
  summary_global_electric_vehicles as KnowledgeSummary,
  summary_global_homelessness as KnowledgeSummary,
  summary_internet_access as KnowledgeSummary,
];

/** Returns the ISO week string for a given date, e.g. "2026-W35". */
function getISOWeekId(date: Date = new Date()): string {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayOfWeek = d.getUTCDay() || 7; // Monday = 1 ... Sunday = 7
  d.setUTCDate(d.getUTCDate() + 4 - dayOfWeek);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const weekNumber = Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
  return `${d.getUTCFullYear()}-W${String(weekNumber).padStart(2, '0')}`;
}

/** Returns a monotonically increasing week index, stable across years. */
function getAbsoluteWeekIndex(date: Date = new Date()): number {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dow = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() - (dow - 1)); // rewind to Monday
  const EPOCH_MS = Date.UTC(2000, 0, 3);    // Monday 2000-01-03
  return Math.round((d.getTime() - EPOCH_MS) / (7 * 24 * 60 * 60 * 1000));
}

/**
 * Returns the puzzle for the current ISO week.
 * When no exact match exists, cycles through all puzzles in publish-date order
 * so every week always has something to show.
 */
export function getCurrentWeeklyPuzzle(): WeeklyPuzzle {
  const weekId = getISOWeekId();
  const exact = PUZZLES.find((p) => p.week_id === weekId);
  if (exact) return exact;

  // No puzzle authored for this week — cycle through available puzzles
  const sorted = [...PUZZLES].sort((a, b) => a.publish_date.localeCompare(b.publish_date));
  return sorted[getAbsoluteWeekIndex() % sorted.length];
}

export function getPuzzleById(id: string): WeeklyPuzzle | null {
  return PUZZLES.find((p) => p.id === id) ?? null;
}

export function getSummaryById(id: string): KnowledgeSummary | null {
  return SUMMARIES.find((a) => a.id === id) ?? null;
}
